# PUT http://localhost:3000/api/missionvision
# Content-Type: application/json

# {
#     "id": "clnwxhz280000hsfgwnyhck8x",
#     "title": "Edit ko ulit",
#     "description": "Option",
# }

# GET  http://localhost:3000/api/appointment
# Content-Type: application/json

# { 

# }

# POST http://localhost:3000/api/appointment
# Content-Type: application/json

# {
#   "date": "2023-12-12",
#   "time": "05:58 PM",
#   "reason": "Behavior Maladjustments",
#   "course": "BSIT",
#   "year": 1
# }


# DELETE http://localhost:3000/api/hotline
# Content-Type: application/json

# {
#     "id": "clo27a5me0000hsow6oy6jocm",
# }



